title: "Dasabodha Grantha Telugu Lyrics"
description: "Dashakams and Samasams in Telugu"
baseurl: "" # keep empty for gsrgnk.github.io
url: "https://gsrgnk.github.io"

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

# Permalink structure
permalink: /:title/
