name: ✨ Feature Request
about: Suggest a new feature or improvement for Om Namo Narayanaya Bhakthi Channel
title: "[Feature] "
labels: enhancement
assignees: ''

body:
  - type: input
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Describe the feature you want added"
      placeholder: "Add search by Dashakam or Samasam number"
      required: true
  - type: input
    id: problem_solved
    attributes:
      label: "Problem This Solves"
      description: "Why is this feature needed?"
      placeholder: "Users cannot find specific Samasam easily"
      required: true
  - type: input
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Any other options you considered"
      placeholder: "Manual scroll through posts"
      required: false
  - type: input
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Anything else to mention"
      placeholder: "Optional"
      required: false
